export const GLOBAL = {
    PROGRESS_CHANGE: "PROGRESS_CHANGE",
    SET_NOTIFICATION_VALUE: "SET_NOTIFICATION_VALUE",
    SET_SHOW_NAVBAR: "SET_SHOW_NAVBAR",
    SET_FOLD_OPEN: "SET_FOLD_OPEN",
    SET_SHOW_MOBILE_NAV: 'SET_SHOW_MOBILE_NAV',
    SET_NAV_TEXT: 'SET_NAV_TEXT,'
}