export const USER = {
    SET_PORTFOLIO_DATA: "SET_PORTFOLIO_DATA",
    SET_TOKEN: 'SET_TOKEN',
    SET_USER_DATA: 'SET_USER_DATA',
    SET_WALLET_INFO: 'SET_WALLET_INFO',
    SET_USER_TRANSACTIONS: 'SET_USER_TRANSACTIONS',
    SET_AUTO_SCHEDULE: 'SET_AUTO_SCHEDULE'
}